# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Education Network' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Education Network
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'WSTagsField'
  pod ‘youtube-ios-player-helper’
  pod 'SideMenuSwift'

  target 'Education NetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Education NetworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
